// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';

// Define your application routes here ONLY ONCE
export const routes: Routes = [
  { path: '', component: HomeComponent },
  // Add other routes as needed:
  // { path: 'product/:id', component: ProductDetailComponent },
];
