// Code Generated by Sidekick is for learning and experimentation purposes only.

import { Component, OnInit } from '@angular/core';
import { NgFor } from '@angular/common';
import { DatabaseService, TeamMember } from '../../services/database.service'; // Use your new backend service!

@Component({
  selector: 'app-team',
  standalone: true,
  imports: [NgFor],
  templateUrl: './team.component.html'
})
export class TeamComponent implements OnInit {

  members: TeamMember[] = [];

  constructor(private databaseService: DatabaseService) {}

  ngOnInit() {
    this.databaseService.getTeamMembers().subscribe(members => {
      // Ensure image path is correct
      this.members = members.map(member => ({
        ...member,
        image: member.image.startsWith('/assets/') ? member.image : '/assets/' + member.image
      }));
    });
  }

}
