// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Component, OnInit } from '@angular/core';
import { NgFor, NgStyle, NgClass } from '@angular/common';
import { RouterLink } from '@angular/router';

// Adjust the path below if needed for your service location
import { ImageService } from '../../services/image.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink, NgFor, NgStyle, NgClass],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  images: string[] = [];
  banner = '';

  constructor(private imageService: ImageService) {}

  ngOnInit(): void {
    // Assuming getProductImage takes a product ID (1-5) and returns an image URL
    this.images = [1, 2, 3, 4, 5].map(i => this.imageService.getProductImage(i));
    this.banner = this.imageService.getBannerImage();
  }
}
