// Code Generated by Sidekick is for learning and experimentation purposes only.

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpService } from './http.service';

export interface Review {
  id: number;
  name: string;
  rating: number;
  comment: string;
}

export interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  // Extend with other fields if present in db.json
  originalPrice?: number | null;
  rating?: number;
  stock?: number;
  category?: string;
  description?: string;
  images?: string[];
  mainImage?: string;
  additionalInfo?: string;
  shippingInfo?: string;
  reviews?: Review[];
}

export interface TeamMember {
  id: number;
  name: string;
  position: string;
  image: string;
}
export interface Category {
  id: number;
  name: string;
}


@Injectable({ providedIn: 'root' })
export class DatabaseService {
  constructor(private http: HttpService) {}

  // PRODUCTS
  getProducts(): Observable<Product[]> { return this.http.get<Product[]>('/products'); }
  getProduct(id: number): Observable<Product> { return this.http.get<Product>(`/products/${id}`); }

  // CATEGORIES
  getCategories(): Observable<string[]> { return this.http.get<string[]>('/categories'); }

  // TEAM MEMBERS
  getTeamMembers(): Observable<TeamMember[]> { return this.http.get<TeamMember[]>('/teamMembers'); }
}
