// Code Generated by Sidekick is for learning and experimentation purposes only.

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

// Interfaces (keep the ones you had as before)
export interface Review {
  id: number;
  name: string;
  rating: number;
  comment: string;
}

export interface Product {
  id: number;
  name: string;
  price: number;
  originalPrice?: number | null;
  rating: number;
  stock: number;
  category: string;
  description: string;
  images: string[];
  mainImage: string;
  additionalInfo: string;
  shippingInfo: string;
  reviews: Review[];
}

export interface TeamMember {
  id: number;
  name: string;
  position: string;
  image: string;
}

@Injectable({ providedIn: 'root' })
export class ProductService {
  private apiUrl = 'http://localhost:3000'; // Adjust as needed

  constructor(private http: HttpClient) {}

  getProducts(): Observable<Product[]> {
    return this.http.get<Product[]>(`${this.apiUrl}/products`);
  }

  getProductById(id: number): Observable<Product> {
    return this.http.get<Product>(`${this.apiUrl}/products/${id}`);
  }

  getCategories(): Observable<string[]> {
    return this.http.get<string[]>(`${this.apiUrl}/categories`);
  }

  getTeamMembers(): Observable<TeamMember[]> {
    return this.http.get<TeamMember[]>(`${this.apiUrl}/teamMembers`);
  }
}
